stages:
  - build
#   - test


services:
  - docker:20.10.12-dind


.default_vars:
  tags:
    - striker-shared-runner-dind


variables:
  ENV_NAME:
    value: "none"
    options:
      - "none"
      - "dev"
    description: "Run deploy jobs. Target deploy server."

  RELEASE_VERSION_TAG:
    value: ""
    description: "If empty, an auto-increment tag will start. Target version number."

  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip" # Change pip's cache directory to be inside the project directory since we can only cache local items.


# test:
#   stage: test
#   extends: .default_vars
#   image: python:3.9-slim
#   cache:                      # Pip's cache doesn't store the python packages
#     paths:                    # https://pip.pypa.io/en/stable/topics/caching/
#       - .cache/pip
#   script:
#     - python -V
#     - pip install mypy
#     - pipenv install --skip-lock
#     - mypy .
#   only:
#     - merge_requests


build:
  stage: build
  extends: .default_vars
  image: docker-repository.strikersoft.dev/striker-common/docker-awscli-ecscli:latest
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_TLS_VERIFY: ""
  script:
    - echo $DOCKER_PASS | docker login -u "$DOCKER_USER" --password-stdin docker-repository.strikersoft.dev
    - echo -------------------------------------- building harbor images -------------------------------------------------------
    - docker build -t vattenfall/gridcapacity .
    - docker tag vattenfall/gridcapacity docker-repository.strikersoft.dev/vattenfall/gridcapacity:$CI_COMMIT_TAG
    - docker push docker-repository.strikersoft.dev/vattenfall/gridcapacity:$CI_COMMIT_TAG

  rules:
    - if: "$CI_COMMIT_TAG"
